### ISSUE TITLE
Incorrect step in ECS guide

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/guides#213]
Moved from https://github.com/weaveworks/integrations/issues/104

> https://www.weave.works/guides/service-discovery-and-load-balancing-with-weave-on-amazon-ecs-2/
> In the manual setup, it all works but wont connect to cloud.
> 
> `echo "SCOPE_AAS_PROBE_TOKEN=XXXX" >> ./user-data.sh`
> Should be
> `echo "echo SERVICE_TOKEN=XXXX >> /etc/weave/scope.config" >> ./user-data.sh`

**Comment by mnwalker** [comment]
And almost forgot to mention the other one right next to it since I spotted that one right away so it didn't cause me any issues.
But in the purpose of accuracy and to avoid issues for anyone else...

 `cp /data/set-ecs-cluster-name.sh ./user-data.sh`
Should be (unless you installed in base filesystem)
`cp data/set-ecs-cluster-name.sh ./user-data.sh`

**Comment by mnwalker** [comment]
Pull request made now I have seen the page is in git so can help fix it myself.

**Comment by 2opremio** [comment]
Fixed via #214
