### ISSUE TITLE
weave bits obscured by seas of infrastructure setup and shell scripts

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#6]
The self-contained, start from scratch nature of the guides makes it quite difficult to see the weave bits. This is especially a problem for experienced users, who know perfectly well how to provision a bunch of machines for testing, and just want to skip to the 'interesting' stuff.

Not sure what to do about that. Perhaps have a very clear delineation in each guide between the infrastructure setup, and weave bits. Which might be tricky in some cases.

**Comment by merrells** [comment]
Could have beginner and advanced versions… downside is more guides to maintain.

> On Jun 25, 2015, at 12:28 PM, Matthias Radestock notifications@github.com wrote:
> 
> The self-contained, start from scratch nature of the guides makes it quite difficult to see the weave bits. This is especially a problem for experienced users, who know perfectly well how to provision a bunch of machines for testing, and just want to skip to the 'interesting' stuff.
> 
> Not sure what to do about that. Perhaps have a very clear delineation in each guide between the infrastructure setup, and weave bits. Which might be tricky in some cases.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/weaveworks/guides/issues/6.

## 

John Merrells

blog: http://johnmerrells.com
profile: http://linkedin.com/in/merrells
email: john@merrells.com
twitter: @merrells
phone: 415-244-5808

**Comment by Stellaverse** [comment]
Eliminate anything to do with provisioning altogether. If someone doesn't know how to spin up their own instances to test out Weave then what exactly do they need the software for in the first place?

You could offer the 'Weave-In-A-Box' versions of the guides too, but the primary guides should assume knowledge of how to provision basic linux boxes.

**Comment by ljsommer** [comment]
I am with Stellaverse- to a point. Provisioning in the form of Vagrantfiles and Ansible playbooks (etc) are totally fine because you get a line by line command history of what needs to be executed and how it talks.

My major gripe is the attempt to use Docker Machine to make things simpler/easier. Think of your target audience for this. We're early adopters by definition of using Weave and we're most likely using it to couple it with Swarm and by extension, Compose.

My coworker now has a Swarm + Weave cluster up but he did it using Machine so we're both totally confused as to how any of these pieces should talk to each other. This is very important information as we aren't going to use Machine in production, so we have this big knowledge gap that isn't covered by any documentation or explained in any meaningful way. "Use Docker-Machine" is not documentation. 

I want to see diagrams of use cases with dependencies and commands. I want to see these because that's what it takes to design an infrastructure for production.

**Comment by errordeveloper** [comment]
@rade a self-contained from-scratch type of guide let's the author guarantee that things will work for most folks and avoid having to handle tiny distro-specific differences whether in the code or the text.

**Comment by errordeveloper** [comment]
@ljsommer I believe the majority of the guides that we have here cover what you are looking for, modulo the details of config tool type/flavour. Your issue with usage of Machine in the latest guide that I wrote is clear to me, and I am planning to write something that would use Vagrant instead. Am I correct in assuming that you would be okay with Vagrant example that you can run and then take what you have learned and implement on your own Vagrant setup that might use a different Linux distro etc?

**Comment by errordeveloper** [comment]
> I want to see diagrams of use cases with dependencies and commands. I want to see these because that's what it takes to design an infrastructure for production.

Ok, I'll open a separate ticket for that, kept meaning to do this since a while.

**Comment by errordeveloper** [comment]
@merrells I've been thinking of various different things in that respect... may be it's more about having beginner part where it's do A, B & C, and then there is an advanced explanation of how it works exactly part (which might even just hide in code comments in some cases, perhaps).

**Comment by errordeveloper** [comment]
@Stellaverse I agree with what you are suggesting in general, however please note that the difficult bits appear when things like Swarm/Mesos/Kubernetes come into play, while without those README and the docs.weave.works are certainly more then enough for quite a few users out there.

**Comment by abuehrle** [comment]
I have been thinking about this issue, about advanced users vs. beginners and am in the process of working on a plan. 

But briefly, I think the guides should grouped into: 
1. Tutorial/getting started guides, these would be what you have right now with simple examples to get up and running and I would remove the bits that are repetitive,i.e. the section on installing the virtualboxes and vagrant and put these into one section, where it can be linked to it if someone needs to know that. 
2. Production/real world topics for more advanced users
3. Put the documentation on the website with a linked table of contents on the left-hand-side (like the way Docker and Vagrant have theirs) and make it more topic -based, rather than self-contained chapters.

**Comment by errordeveloper** [comment]
Just for the record, one very general idea is to have well-maintained higher level guides and one-off  demos (mostly quite a bit more advanced, best effort maintenance).
